name: Format

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm install prettier

      - run: npx prettier --check .

  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    container: ghcr.io/jannik2099/pms-utils-gentoo-ci:latest

    steps:
      - uses: actions/checkout@v4

      - name: install botan
        run: |
          emerge botan

      - name: configure
        run: |
          . /etc/profile
          meson setup build

      - name: check
        run: |
          . /etc/profile
          ninja -C build clang-format-check

  meson-format:
    name: meson format
    runs-on: ubuntu-latest
    container: ghcr.io/jannik2099/pms-utils-gentoo-ci:latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          meson format --recursive --check-only .
