name: Rocky Linux

on:
  pull_request:
  # github has yet to figure out how to do fast-forward merges without changing the commit hash
  # so we need to rebuild from main to get the correct hash
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/rockylinux/rockylinux:10

    steps:
      - uses: actions/checkout@v4

      - name: install build deps
        run: |
          dnf install -y python3-pip gcc-c++ libstdc++ git cmake xz
          pip3.12 install meson ninja

      - name: install botan
        run: |
          cd
          curl -s -L https://botan.randombit.net/releases/Botan-3.8.1.tar.xz | tar --xz --extract
          cd Botan-3.8.1
          python3.12 ./configure.py --build-tool=ninja --disable-deprecated-features --without-documentation
          ninja install

      - name: configure
        run: |
          PKG_CONFIG_PATH=/usr/local/lib/pkgconfig meson setup --prefix=/root/s3cpp_install --strip --prefer-static --wrap-mode=forcefallback --buildtype=release -Db_lto=true build

      - name: compile
        run: |
          meson compile -C build

      - name: test
        run: |
          meson test -C build

      - name: install
        run: |
          meson install -C build

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: tools
          path: /root/s3cpp_install/bin/*
          if-no-files-found: error
